apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
    disableNameSuffixHash: true
    labels:
      app: ghost

resources:
  - ./base/namespace.yaml
  - ./base/secrets.yaml
  - ./app/ghost/deployment.yaml
  - ./app/ghost/configmap.yaml
  - ./app/ghost/secrets.yaml
  - ./app/ghost/service.yaml
  - ./app/ghost/pvc.yaml
  - ./app/ghost/ingress.yaml
  - ./app/mysql/deployment.yaml
  - ./app/mysql/service.yaml
  - ./app/mysql/pvc.yaml