apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage