apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: do-block-storage